name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install dependencies
      run: |
         pipenv install --dev
    - name: Run Test
      run: |
        source "$(pipenv --venv 2>/dev/null)/bin/activate"
        python -m pytest \
          --cov=smalldiff \
          --cov-branch \
          --cov-report=xml \
          --cov-fail-under=80
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: dipanjal/smalldiff